import { backendLog } from '../../api/backend';

const linkedNoteCleanup = new Set<string>();
const LINKED_NOTE_MARKER = '[gdl-link-note]';
const NOTE_API_TIMEOUT_MS = 3000;

/** Steam's GameNotes bridge can remain pending when Notes is unavailable or
 * Steam is rebuilding the shortcut model. Note cleanup is optional and must
 * never hold a link transaction (or a library route) open indefinitely. */
function withTimeout<T>(promise: Promise<T>, timeoutMs: number, errorCode: string): Promise<T> {
	return new Promise<T>((resolve, reject) => {
		const timer = setTimeout(() => reject(new Error(errorCode)), timeoutMs);
		promise.then(value => { clearTimeout(timer); resolve(value); }, error => { clearTimeout(timer); reject(error); });
	});
}

function noteFileName(shortcutName: string): string {
	return 'notes_shortcut_' + shortcutName.replace(/[!-/:-@ [\\\]^`]/g, '_');
}

/**
 * Remove only notes previously generated by NativeGameLink. User-authored
 * notes are deliberately preserved even though the plugin leaves Notes empty
 * by default for non-Steam and legacy-linked games.
 */
export async function clearLinkedGameNote(shortcutName: string): Promise<boolean> {
	const gameNotes = (window as any).SteamClient?.GameNotes;
	if (!gameNotes || typeof gameNotes.GetNotes !== 'function' || typeof gameNotes.SaveNotes !== 'function') {
		backendLog('Linked note cleanup skipped: Steam GameNotes API unavailable');
		return false;
	}
	const safeName = String(shortcutName || '').trim();
	if (!safeName) return false;
	const fileName = noteFileName(safeName);
	const imageDir = fileName + '_images/';
	try {
		const loaded = await withTimeout(
			Promise.resolve(gameNotes.GetNotes(fileName, imageDir)),
			NOTE_API_TIMEOUT_MS,
			'game_notes_get_timeout',
		);
		let notes: any[] = [];
		if (typeof loaded?.notes === 'string' && loaded.notes.trim()) {
			try {
				const parsed = JSON.parse(loaded.notes);
				if (Array.isArray(parsed?.notes)) notes = parsed.notes;
			} catch (error) { backendLog('Linked note cleanup parse failed: ' + error); }
		}
		const remaining = notes.filter(note => !String(note?.id || '').startsWith('gdl_link_')
			&& !String(note?.content || '').includes(LINKED_NOTE_MARKER));
		if (remaining.length === notes.length) return false;
		const result = await withTimeout(
			Promise.resolve(gameNotes.SaveNotes(fileName, JSON.stringify({ shortcut_name: safeName, notes: remaining }))),
			NOTE_API_TIMEOUT_MS,
			'game_notes_save_timeout',
		);
		if (typeof gameNotes.SyncToServer === 'function') {
			try {
				await withTimeout(Promise.resolve(gameNotes.SyncToServer()), NOTE_API_TIMEOUT_MS, 'game_notes_sync_timeout');
			} catch (error) { backendLog('Linked note cleanup sync skipped: ' + error); }
		}
		const ok = result === undefined || result === 1;
		backendLog(`Linked game note ${ok ? 'removed' : 'cleanup failed'} for shortcut ${safeName}`);
		return ok;
	} catch (error) {
		backendLog('Linked note cleanup failed: ' + error);
		return false;
	}
}

/** Clean a legacy generated note once when its linked library page is opened. */
export async function syncLinkedGameNote(shortcutName: string, _data?: unknown, steamAppId = ''): Promise<void> {
	const safeShortcutName = String(shortcutName || '').trim();
	if (!safeShortcutName) return;
	const key = `${steamAppId}:${safeShortcutName}`;
	if (linkedNoteCleanup.has(key)) return;
	linkedNoteCleanup.add(key);
	await clearLinkedGameNote(safeShortcutName).catch(error => backendLog('Linked note cleanup skipped: ' + error));
}

export function clearLinkedNoteSyncState(): void {
	linkedNoteCleanup.clear();
}
